# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 58372945+em4n0n@users.noreply.github.com
author_name: em4n0n
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: Digital_Marketplace

